# Generated by Django 5.1.6 on 2026-06-15 14:48

import django.db.models.deletion
import resume_checker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_checker', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resume_checker.models.user_resume_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_result', models.JSONField(blank=True, default=None, null=True)),
                ('match_score', models.FloatField(blank=True, default=None, null=True)),
                ('skills_extracted', models.JSONField(blank=True, default=list)),
                ('experience_extracted', models.CharField(blank=True, default='', max_length=100)),
                ('education_extracted', models.CharField(blank=True, default='', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
