# Generated by Django 5.1.6 on 2026-06-16 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_checker', '0005_userresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='certifications_extracted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userresume',
            name='email_extracted',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userresume',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userresume',
            name='name_extracted',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userresume',
            name='phone_extracted',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userresume',
            name='projects_extracted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userresume',
            name='resume_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_questions', models.JSONField(blank=True, default=list)),
                ('behavioral_questions', models.JSONField(blank=True, default=list)),
                ('role_specific_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='resume_checker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='resume_checker.userresume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_roles', models.JSONField(blank=True, default=list, help_text='List of {role, confidence, reason} dicts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_recommendations', to='resume_checker.userresume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resume_checker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resume_checker.userresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ResumeJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_score', models.FloatField(default=0, help_text='Cosine similarity score 0-100')),
                ('keyword_score', models.FloatField(default=0, help_text='Keyword overlap score 0-100')),
                ('overall_score', models.FloatField(default=0, help_text='Weighted composite score 0-100')),
                ('tier', models.CharField(choices=[('excellent', 'Excellent Match'), ('good', 'Good Match'), ('average', 'Average Match'), ('poor', 'Poor Match')], default='poor', max_length=20)),
                ('skills_matched', models.JSONField(blank=True, default=list)),
                ('skills_missing', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='resume_checker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='resume_checker.userresume')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('resume', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('match_percentage', models.FloatField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Improvement recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='resume_checker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='resume_checker.userresume')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
