import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LocationOn, Work, AccessTime, BookmarkBorder, Bookmark } from '@mui/icons-material';
const typeLabels = {
    'full-time': 'Full-time',
    'part-time': 'Part-time',
    'contract': 'Contract',
    'internship': 'Internship',
    'remote': 'Remote',
};
export const JobCard = ({ job, onApply, onView, onSave, isSaved = false, showMatchScore = false, compact = false, }) => {
    const matchColor = (job.match_score || 0) >= 80 ? 'text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-900/20'
        : (job.match_score || 0) >= 60 ? 'text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20'
            : 'text-orange-600 dark:text-orange-400 bg-orange-50 dark:bg-orange-900/20';
    return (_jsxs("div", { className: "card-base p-5 card-hover group", onClick: () => onView?.(job), children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "flex items-start gap-3 flex-1 min-w-0", children: [_jsx("div", { className: "w-11 h-11 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center flex-shrink-0 shadow-sm", children: _jsx("span", { className: "text-white font-bold text-sm", children: job.company.charAt(0) }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h3", { className: "font-semibold text-gray-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors truncate", children: job.job_title }), _jsx("p", { className: "text-sm text-gray-600 dark:text-zinc-400", children: job.company })] })] }), _jsxs("div", { className: "flex items-center gap-2 flex-shrink-0", children: [showMatchScore && job.match_score && (_jsxs("span", { className: `px-2 py-1 rounded-lg text-xs font-bold ${matchColor}`, children: [job.match_score, "% Match"] })), onSave && (_jsx("button", { onClick: (e) => { e.stopPropagation(); onSave(job); }, className: "p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-[#1a1a1a] transition-colors", "aria-label": isSaved ? 'Unsave job' : 'Save job', children: isSaved
                                    ? _jsx(Bookmark, { style: { fontSize: 20 }, className: "text-blue-600" })
                                    : _jsx(BookmarkBorder, { style: { fontSize: 20 }, className: "text-gray-400" }) }))] })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3 mt-3 text-xs text-gray-500 dark:text-zinc-400", children: [_jsxs("span", { className: "inline-flex items-center gap-1", children: [_jsx(LocationOn, { style: { fontSize: 14 } }), job.location] }), _jsxs("span", { className: "inline-flex items-center gap-1", children: [_jsx(Work, { style: { fontSize: 14 } }), typeLabels[job.job_type] || job.job_type] }), job.experience_required > 0 && (_jsxs("span", { className: "inline-flex items-center gap-1", children: [_jsx(AccessTime, { style: { fontSize: 14 } }), job.experience_required, "+ years"] })), job.salary_range && (_jsx("span", { className: "font-medium text-gray-700 dark:text-zinc-300", children: job.salary_range }))] }), !compact && (_jsxs("div", { className: "flex flex-wrap gap-1.5 mt-3", children: [job.required_skills.slice(0, 5).map(skill => (_jsx("span", { className: "px-2 py-0.5 bg-gray-100 dark:bg-[#1a1a1a] text-gray-600 dark:text-zinc-300 rounded-md text-xs font-medium", children: skill }, skill))), job.required_skills.length > 5 && (_jsxs("span", { className: "px-2 py-0.5 text-gray-400 dark:text-zinc-500 text-xs", children: ["+", job.required_skills.length - 5, " more"] }))] })), _jsxs("div", { className: "flex items-center justify-between mt-4 pt-3 border-t border-gray-100 dark:border-[#222222]/50", children: [_jsxs("div", { className: "flex items-center gap-3 text-xs text-gray-500 dark:text-zinc-400", children: [_jsxs("span", { children: [job.applicant_count, " applicants"] }), _jsxs("span", { children: ["Posted ", new Date(job.posted_at).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })] })] }), onApply && (_jsx("button", { onClick: (e) => { e.stopPropagation(); onApply(job); }, className: "btn-primary text-xs px-3 py-1.5", children: "Apply Now" }))] })] }));
};
export default JobCard;
